version: "3"
services:
  armysql:
    environment: 
    - MYSQL_ROOT_PASSWORD=Myfriendwa@123
    image: mysql
    ports: 
    - "3306:3306"
    volumes: 
    - "E:\\ext\\mysqlconf:/etc/mysql/conf.d"
    - "E:\\ext\\mysqldata:/var/lib/mysql"
  arjboss:
    image: jboss/wildfly
    ports: 
    - "8080:8080"
    - "9990:9990"
    volumes: 
    - "E:\\ext\\ear:/opt/jboss/wildfly/standalone/deployments/"
    - "E:\\ext\\logs\\jboss:/opt/jboss/wildfly/standalone/log/"
    