
package com.arsoft.projects.artutorial.learning.soap.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldService", targetNamespace = "http://server.soap.learning.artutorial.projects.arsoft.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWorldService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.soap.learning.artutorial.projects.arsoft.com/HelloWorldService/sayHelloRequest", output = "http://server.soap.learning.artutorial.projects.arsoft.com/HelloWorldService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
